#!/bin/sh

# This is a script which installs all the items in His Grace's Software Suite.
# It assumes that the actions performed in the pre-installer, i.e. setting up
# Git, have already been carried out.

# Constants.
HGSS_DIR="$HOME/hgss/"
CHROME_DEB="google-chrome-stable_current_amd64.deb"

#############
# SET FLAGS #
#############

chrome_os_flag="n"
ignore_errors_flag="n"
minimal_flag="n"

for flag in $@; do
    if [ $flag = "--chrome-os" ]; then
        chrome_os_flag="y"
    elif [ $flag = "--ignore-errors" ]; then
        ignore_errors_flag="y"
    elif [ $flag = "--minimal" ]; then
        minimal_flag="y"
    fi
done

# Make any non-zero returns throw an error, if appropriate.
if [ $ignore_errors_flag = "n" ]; then
    set -e
fi

##########
# BASICS #
##########

# Let's get cracking...
cd $HOME
sudo apt update
sudo apt --yes upgrade

# Install Google Chrome.
if [ $chrome_os_flag = "n" ]; then
    wget https://dl.google.com/linux/direct/$CHROME_DEB
    sudo dpkg -i $CHROME_DEB
    rm $CHROME_DEB
fi

# Install PIP3 and PyLint.
sudo apt --yes install python3-pip
pip3 install pylint

# Install the extra plugins for Gedit.
sudo apt --yes install gedit-plugins

# Change the wallpaper.
cd $HGSS_DIR
sudo cp wallpaper.jpg /usr/share/backgrounds/paphos-wallpaper.jpg || true
gsettings set org.gnome.desktop.background picture-uri file:////usr/share/backgrounds/paphos-wallpaper.jpg || true
cd $HOME

################
# THE SERAGLIO #
################

if [ ! -d the-seraglio ] && [ $minimal_flag = "n" ]; then
    # Install SQLite and browser.
    sudo apt --yes install sqlite3
    sudo apt --yes install sqlitebrowser
    # Install NodeJS and NPM.
    sudo apt --yes install nodejs
    sudo apt --yes install npm
    # Download and install the repo.
    git clone https://github.com/chancellorofpaphos/the-seraglio.git
    cd the-seraglio
    npm install
    cd ..
fi

############
# CHANCERY #
############

if [ ! -d chancery-b-paphos ] && [ $minimal_flag = "n" ]; then
    # Install LaTeX.
    sudo apt --yes install texlive-full
    # Download the repo for Formulary A.
    git clone https://github.com/chancellorofpaphos/chancery-paphos.git
    # Download and install the repo for Formulary B.
    git clone https://github.com/chancellorofpaphos/chancery-b-paphos.git
    cd chancery-b-paphos
    sh install_externals
    cd ..
fi

#####################
# OTHER THIRD PARTY #
#####################

# Install Inkscape.
sudo apt --yes install inkscape

# If using a Chromebook, install some basic utilities.
if [ $chrome_os_flag = "y" ]; then
    sudo apt --yes install chromium
    sudo apt --yes install eog
    sudo apt --yes install nautilus
fi

# That's it!
echo "***** HGSS installed successfully! *****"
